### ISSUE TITLE
Small corrections for installation steps

### ISSUE THREAD

**Issue by hiddenillusion** [ciscocsirt/GOSINT#1]
Both are located under https://github.com/ciscocsirt/gosint#step-by-step

1. can't change to user _gosint_ without sudo'ing
```
sudo useradd -m gosint
su gosint
```

`sudo su gosint`

2. capitalization for what you clone and what you cd into should match (GOSINT vs gosint)
```
git clone https://github.com/ciscocsirt/GOSINT
cd gosint
```

`cd GOSINT`

**Comment by iamtmehdi** [comment]
Thank you for submitting the corrections, I have updated the README.
