### ISSUE TITLE
127.0.0.1:8000

### ISSUE THREAD

**Issue by salola** [ciscocsirt/GOSINT#11]
Hey!
Macine is Ubuntu 16.04. I used bash install. Фfter installation at the address 127.0.0.1:8000 404 page not found. 
Output of command -lntup 

tcp 0 0 127.0.1.1:53 0.0.0.0:* LISTEN - 
tcp 0 0 127.0.0.1:631 0.0.0.0:* LISTEN - 
tcp 0 0 127.0.0.1:8000 0.0.0.0:* LISTEN 4326/gosint 
tcp 0 0 127.0.0.1:27017 0.0.0.0:* LISTEN - 
tcp 0 0 0.0.0.0:80 0.0.0.0:* LISTEN - 
tcp6 0 0 ::1:631 :::* LISTEN - 
udp 0 0 0.0.0.0:58709 0.0.0.0:* - 
udp 0 0 0.0.0.0:38657 0.0.0.0:* - 
udp 0 0 127.0.1.1:53 0.0.0.0:* - 
udp 0 0 0.0.0.0:68 0.0.0.0:* - 
udp 0 0 0.0.0.0:5353 0.0.0.0:* - 
udp6 0 0 :::51135 :::* - 
udp6 0 10240 :::5353 :::* -

API response from http://localhost/api/pre/ and get a JSON response of {"message": "none found"}
PHP it's OK.
Help me, please.

**Comment by iamtmehdi** [comment]
Hello, Can you navigate to http://localhost/ and see what happens?

**Comment by salola** [comment]
Thank you! The Error was in the server config.

**Comment by iamtmehdi** [comment]
You're welcome!
