### ISSUE TITLE
GUI not showing indicators

### ISSUE THREAD

**Issue by rt5v3y02fk** [ciscocsirt/GOSINT#12]
I was able to get past my AJAX error by starting the gosint process.  Although the Welcome to GOSINT GUI comes up, the GUI does not load any indicator metrics.  Also are there any recommended feeds?  I have twitter and alienvault setup I just don't get anything listed in the GUI.

**Comment by blueteam1** [comment]
Hey debinfosec,

Do you see any output from the gosint backend process indicating that it is finding indicators via twitter or alienvault?  For twitter, it has to find relevant indicators via the parsers in the tweets, otherwise it wont report anything.  For alienvault, it should start backloading indicators immediately.

**Comment by rt5v3y02fk** [comment]
In the terminal window, it says the twitter and alienvault feeds are up, but nothing shows in the web GUI. One other request can you provide a list of feeds you recommend following in GOSINT?  I have pics attached.  
![image](https://user-images.githubusercontent.com/31938311/32951600-75b5d374-cb78-11e7-9c8d-ab6ada5abbcf.png)
![image](https://user-images.githubusercontent.com/31938311/32951629-95360750-cb78-11e7-822f-ecdeab65cade.png)
![image](https://user-images.githubusercontent.com/31938311/32951639-9e925d1c-cb78-11e7-9503-f88516a2d5b6.png)

**Comment by blueteam1** [comment]
More than likely what's happening is that the twitter parser is not finding any suitable indicators via the parser and also, the Alienvault feature only runs once a day at midnight for the configured server.  

A good twitter account to test the twitter parsing functionality with is https://twitter.com/HoneyPyLog as it is pretty noisy with indicators that will be parsed.  I just tested this account today with a fresh install, so I know it should work for you as long as everything is setup properly.

**Comment by rt5v3y02fk** [comment]
I installed Ubuntu 16.04, so is that ok?  For the twitter account I figured out to use deb_infosec or HoneyPyLog without the @.  Also Firefox by default blocks dangerous content, so I had to turn this off to get the GUI to display info.  Is there a free Umbrella API like alienvault has?  Yeah finally got this to work!!!!

**Comment by rt5v3y02fk** [comment]
Can you give us some indicator feeds you recommend?  I'm a compliance person, not SOC, but love getting to have this visibility into threats.  I have a bunch of twitter accounts, but need the other feeds.  Is CRITS recommended?  It looks like it is a separate install.  One more thing how does GOSINT pull in info from research papers?
