### ISSUE TITLE
Web interface is missing tabs

### ISSUE THREAD

**Issue by Catpurr** [ciscocsirt/GOSINT#18]
Greetings! I used the bash installer script to install GOSINT. When I navigated to the dashboard at localhost after installation to set my keys, I was greeted with an interface lacking any tabs.

![image](https://user-images.githubusercontent.com/19367656/35593646-7222dcac-05de-11e8-9421-66845934d94f.png)

Any suggestions as to how to fix this issue in my installation?

**Comment by iamtmehdi** [comment]
Hello, thanks for trying out GOSINT. This looks like a display resolution issue, can you try zooming out of your browser and see if the side bar appears?

**Comment by iamtmehdi** [comment]
Closed issue as no response and likely display resolution issue.
