### ISSUE TITLE
Error parsing multiple ASNs from reverse lookup

### ISSUE THREAD

**Issue by rshipp** [ciscocsirt/GOSINT#19]
Looks like a bug when whatever ASN lookup you do returns multiple numbers:

```
2018/02/22 09:43:48 Error doing reverse lookup on %v: %v 103.235.224.237 Could not parse ASN (4808 23724 56282): %!s(MISSING): strconv.Atoi: parsing "4808 23724 56282": invalid syntax
2018/02/22 09:43:52 Error doing reverse lookup on %v: %v 103.75.156.237 Could not parse ASN (134877 135216): %!s(MISSING): strconv.Atoi: parsing "134877 135216": invalid syntax
2018/02/22 09:43:59 Error doing reverse lookup on %v: %v 106.75.101.69 Could not parse ASN (4808 23724): %!s(MISSING): strconv.Atoi: parsing "4808 23724": invalid syntax
2018/02/22 09:43:59 Error doing reverse lookup on %v: %v 106.75.18.132 Could not parse ASN (4808 23724): %!s(MISSING): strconv.Atoi: parsing "4808 23724": invalid syntax
```

These IPs are from the CI Army blacklist, http://cinsscore.com/list/ci-badguys.txt, there's about 160 IPs out of the 15k on the list that trigger the error. GOSINT version is latest master as of today, on Ubuntu 16.04.2 LTS, installed through the bash install script.

**Comment by blueteam1** [comment]
Hey Ryan,

Nice catch, I've seen this in our use too.  This is actually a bug with the library we use for that which is https://github.com/ammario/ipisp.  I haven't dug deeper yet to work on a fix, but so far it doesn't seem to cause much issue with it operating with GOSINT.

Thanks

**Comment by rshipp** [comment]
Got it, thanks. :+1: I'll close this issue then. Should I open one upstream or are they already aware of the issue?

**Comment by blueteam1** [comment]
Hey,

We have not notified them yet.  If you want to do that I'm sure they'd appreciate the info so the bug can be tracked (and so would we :) ).  

Thanks!

**Comment by rshipp** [comment]
Upstream fixed in https://github.com/ammario/ipisp/issues/6

**Comment by blueteam1** [comment]
Wow, you're awesome.  Thanks for tracking that down and taking care of it.

Cheers
