### ISSUE TITLE
Error in making AJAX request. Check console for details

### ISSUE THREAD

**Issue by tom-dell** [ciscocsirt/GOSINT#22]
Everytime I navigate to a page I get the same error on the top right hand corner.
![image](https://user-images.githubusercontent.com/29078003/40397744-c089fbcc-5e77-11e8-949f-10b4fca81401.png)

Checking the browser console shows;
![image](https://user-images.githubusercontent.com/29078003/40397766-e14f8fde-5e77-11e8-88e3-8fe143fabb1c.png)

**Comment by iamtmehdi** [comment]
It appears that the API endpoint is not up, and thus returning a 404 Not Found error. Can you verify that you are running the GOSINT binary? 

Also, with the GOSINT binary running, navigate to `http://localhost/api/pre/`. During initial set up when GOSINT has no indicators, the JSON object `{"message": "none found"}` should be returned. Is this present in your browser when you navigate to that page?

**Comment by tom-dell** [comment]
That appeared to be the issue, I presumed it was running in the background, my mistake.

Thank you for your help, hopefully someone else finds this helpful as well.
