### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by vietwow** [ciscocsirt/GOSINT#3]
Hi all,

I think it's better if we have a Dockerfile for GOSINT ;) Thanks.

Best Regards,

**Comment by blueteam1** [comment]
Hey vietwow,
We are in the process of working on that :) Expect to see a docker image soon (and other easy deployment methods).  

I will keep this bug open until we have further word on this.

Thanks

**Comment by Jsitech** [comment]
I created a DockerFile that works perfectly and is good for getting to know GOSINT. I am working on a Multicontainer setup to separate the needed services. Check it out at https://github.com/Jsitech/DockerFiles/tree/master/gosint , It might be of use. The container is also uploaded to the Docker Hub, just do a 

> docker pull jsitech/gosint

**Comment by naipoom** [comment]
Hi Jsitech
What is username and password for access GOSINT.

**Comment by suwitcham** [comment]
very easy setup on docker, any recommend threat intel feed which work ok with GOSINT? I already add virustotal, alienValt, twitter but nothing show on GOSINT dashboard.

**Comment by Jsitech** [comment]
@suwitcham GOSINT does pull from alienvault and other APIs, just not right away. it seems it does it once a day.
