### ISSUE TITLE
metrics.js error

### ISSUE THREAD

**Issue by c0rpse** [ciscocsirt/GOSINT#7]
Uncaught TypeError: Cannot read property 'length' of undefined
    at countUp (metrics.js:50)
    at metrics.js:23
    at d3.min.js:1
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)

error occured in metrics.js:50.
My browser is Chrome 60.0.3112.113(64)

**Comment by iamtmehdi** [comment]
Hello, 
The function of metrics.js is to display some charts about the indicators in GOSINT. This error suggests to me that there are no indicators loaded in GOSINT. Is this a fresh installation of GOSINT or has GOSINT accumulated some indicators?
Thanks.

**Comment by c0rpse** [comment]
Thanks,iamtmehdi.Seems that you're right.
